const devImg = document.querySelectorAll('.dev-info img')
const jim = document.querySelector('.jim')
const max = document.querySelector('.max')
const phil = document.querySelector('.phil')
const ryan = document.querySelector('.ryan')
const csr = document.querySelector('.csr')
const scott = document.querySelector('.scott')

devImg.forEach(value => value.addEventListener('click', coinSpin))
jim.addEventListener('load', leftTopSlide)
max.addEventListener('load', midTopSlide)
phil.addEventListener('load', rightTopSlide)
ryan.addEventListener('load', leftBtmSlide)
csr.addEventListener('load', midBtmSlide)
scott.addEventListener('load', rightBtmSlide)